---
name: Update dependent repositories
on:
  push:
    branches:
      - main
jobs:
  release:
    if: ${{ !startsWith(github.event.commits[0].message, '[github-actions]') }}
    uses: networkservicemesh/.github/.github/workflows/update-dependent-repositories-gomod.yaml@main
    with:
      dependent_repositories: |
        ["cmd-exclude-prefixes-k8s",
        "cmd-forwarder-sriov",
        "cmd-registry-k8s",
        "cmd-nse-supplier-k8s",
        "cmd-forwarder-vpp",
        "cmd-admission-webhook-k8s",
        "cmd-forwarder-ovs"]
    secrets:
      token: ${{ secrets.NSM_BOT_GITHUB_TOKEN }}
